
DROP TABLE IF EXISTS BUSINESS_REGION_CHANNEL_MAPPING;
DROP TABLE IF EXISTS BUSINESS_REGION_COUNTRY_MAPPING;

DROP TABLE IF EXISTS COUNTRY;
CREATE TABLE COUNTRY(
   COUNTRY_ID INT PRIMARY KEY     NOT NULL,
   NAME          VARCHAR(100)    NOT NULL,
   ACTIVE        BOOLEAN,
   ISOCODE_2     CHAR(2),
   ISOCODE_3     CHAR(3)
);

DROP TABLE IF EXISTS BUSINESS_CHANNEL;
CREATE TABLE BUSINESS_CHANNEL (
	BUSINESS_CHANNEL_ID	INT PRIMARY KEY  NOT NULL,
	NAME          VARCHAR(100)    NOT NULL,
	DESCRIPTION   VARCHAR(255),
	ACTIVE        BOOLEAN

);


DROP TABLE IF EXISTS BUSINESS_REGION;
CREATE TABLE BUSINESS_REGION (
	BUSINESS_REGION_ID	INT PRIMARY KEY  NOT NULL,
	PARENT_REGION_ID	INT,
	NAME          VARCHAR(100)    NOT NULL,
	DESCRIPTION   VARCHAR(255),
	ACTIVE        BOOLEAN
);

CREATE TABLE BUSINESS_REGION_CHANNEL_MAPPING (
	BUSINESS_REGION_CHANNEL_MAPPING_ID	INT PRIMARY KEY  NOT NULL,
	BUSINESS_CHANNEL_MAPPING_ID         INT      references BUSINESS_CHANNEL(BUSINESS_CHANNEL_ID),
	BUSINESS_REGION_MAPPING_ID         INT      references BUSINESS_REGION(BUSINESS_REGION_ID)
);


CREATE TABLE BUSINESS_REGION_COUNTRY_MAPPING (
	BUSINESS_REGION_COUNTRY_MAPPING_ID	INT PRIMARY KEY  NOT NULL,
	BUSINESS_REGION_MAPPING_ID          INT      references BUSINESS_REGION(BUSINESS_REGION_ID),
	COUNTRY_MAPPING_ID         			INT      references COUNTRY(COUNTRY_ID)
);